name: CI

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ./gradlew jvmTest

      - name: Archive lib Test Reports
        uses: actions/upload-artifact@v1
        with:
          name: lib_test_reports
          path: lib/build/reports/tests

      - name: Archive lib-threadsafe Test Reports
        uses: actions/upload-artifact@v1
        with:
          name: lib_test_reports
          path: lib/build/reports/tests

  publish-snapshot:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Publish Snapshot
      env:
        SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        GPG_SECRET: ${{ secrets.GPG_SECRET }}
        GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        SNAPSHOT: 'TRUE'
      run: ./gradlew publishSnapShot
